version: '3.8'

services:
  web:
    build:
      context: .
    image: ghcr.io/GitTimeraider/directadmin-emailforwarder:main
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=CH@NGETHISRANDOMCHARACTERSTR1NG
      - DATABASE_URL=sqlite:////app/data/users.db
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
